// <auto-generated />
using System;
using Gunluk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gunluk.Data.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20230104122003_Ilk")]
    partial class Ilk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Gunluk.Data.Gonderi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("DegistirilmeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Resim")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Gonderiler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Baslik = "Örnek Yazı 1",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(8952),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(8941)
                        },
                        new
                        {
                            Id = 2,
                            Baslik = "Örnek Yazı 2",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(8984),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(8984)
                        },
                        new
                        {
                            Id = 3,
                            Baslik = "Örnek Yazı 3",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(8987),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(8986)
                        },
                        new
                        {
                            Id = 4,
                            Baslik = "Örnek Yazı 4",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(8989),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(8989)
                        },
                        new
                        {
                            Id = 5,
                            Baslik = "Örnek Yazı 5",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(8991),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(8991)
                        },
                        new
                        {
                            Id = 6,
                            Baslik = "Örnek Yazı 6",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(8994),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(8993)
                        },
                        new
                        {
                            Id = 7,
                            Baslik = "Örnek Yazı 7",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(8996),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(8995)
                        },
                        new
                        {
                            Id = 8,
                            Baslik = "Örnek Yazı 8",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(8998),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(8997)
                        },
                        new
                        {
                            Id = 9,
                            Baslik = "Örnek Yazı 9",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9000),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(8999)
                        },
                        new
                        {
                            Id = 10,
                            Baslik = "Örnek Yazı 10",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9002),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9001)
                        },
                        new
                        {
                            Id = 11,
                            Baslik = "Örnek Yazı 11",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9004),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9004)
                        },
                        new
                        {
                            Id = 12,
                            Baslik = "Örnek Yazı 12",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9006),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9006)
                        },
                        new
                        {
                            Id = 13,
                            Baslik = "Örnek Yazı 13",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9008),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9008)
                        },
                        new
                        {
                            Id = 14,
                            Baslik = "Örnek Yazı 14",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9010),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9010)
                        },
                        new
                        {
                            Id = 15,
                            Baslik = "Örnek Yazı 15",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9012),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9012)
                        },
                        new
                        {
                            Id = 16,
                            Baslik = "Örnek Yazı 16",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9015),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9014)
                        },
                        new
                        {
                            Id = 17,
                            Baslik = "Örnek Yazı 17",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9017),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9016)
                        },
                        new
                        {
                            Id = 18,
                            Baslik = "Örnek Yazı 18",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9019),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9018)
                        },
                        new
                        {
                            Id = 19,
                            Baslik = "Örnek Yazı 19",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9021),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9020)
                        },
                        new
                        {
                            Id = 20,
                            Baslik = "Örnek Yazı 20",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9023),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9022)
                        },
                        new
                        {
                            Id = 21,
                            Baslik = "Örnek Yazı 21",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9025),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9024)
                        },
                        new
                        {
                            Id = 22,
                            Baslik = "Örnek Yazı 22",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9027),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9026)
                        },
                        new
                        {
                            Id = 23,
                            Baslik = "Örnek Yazı 23",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9029),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9028)
                        },
                        new
                        {
                            Id = 24,
                            Baslik = "Örnek Yazı 24",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9031),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9030)
                        },
                        new
                        {
                            Id = 25,
                            Baslik = "Örnek Yazı 25",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9033),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9032)
                        },
                        new
                        {
                            Id = 26,
                            Baslik = "Örnek Yazı 26",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9035),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9034)
                        },
                        new
                        {
                            Id = 27,
                            Baslik = "Örnek Yazı 27",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9037),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9036)
                        },
                        new
                        {
                            Id = 28,
                            Baslik = "Örnek Yazı 28",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9039),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9038)
                        },
                        new
                        {
                            Id = 29,
                            Baslik = "Örnek Yazı 29",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9041),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9040)
                        },
                        new
                        {
                            Id = 30,
                            Baslik = "Örnek Yazı 30",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9043),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9042)
                        },
                        new
                        {
                            Id = 31,
                            Baslik = "Örnek Yazı 31",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9085),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9084)
                        },
                        new
                        {
                            Id = 32,
                            Baslik = "Örnek Yazı 32",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9087),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9087)
                        },
                        new
                        {
                            Id = 33,
                            Baslik = "Örnek Yazı 33",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9089),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9089)
                        },
                        new
                        {
                            Id = 34,
                            Baslik = "Örnek Yazı 34",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9091),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9091)
                        },
                        new
                        {
                            Id = 35,
                            Baslik = "Örnek Yazı 35",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9093),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9093)
                        },
                        new
                        {
                            Id = 36,
                            Baslik = "Örnek Yazı 36",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9096),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9095)
                        },
                        new
                        {
                            Id = 37,
                            Baslik = "Örnek Yazı 37",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9098),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9097)
                        },
                        new
                        {
                            Id = 38,
                            Baslik = "Örnek Yazı 38",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9100),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9099)
                        },
                        new
                        {
                            Id = 39,
                            Baslik = "Örnek Yazı 39",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9102),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9101)
                        },
                        new
                        {
                            Id = 40,
                            Baslik = "Örnek Yazı 40",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9104),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9103)
                        },
                        new
                        {
                            Id = 41,
                            Baslik = "Örnek Yazı 41",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9106),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9105)
                        },
                        new
                        {
                            Id = 42,
                            Baslik = "Örnek Yazı 42",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9108),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9107)
                        },
                        new
                        {
                            Id = 43,
                            Baslik = "Örnek Yazı 43",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9110),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9109)
                        },
                        new
                        {
                            Id = 44,
                            Baslik = "Örnek Yazı 44",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9112),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9111)
                        },
                        new
                        {
                            Id = 45,
                            Baslik = "Örnek Yazı 45",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9114),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9113)
                        },
                        new
                        {
                            Id = 46,
                            Baslik = "Örnek Yazı 46",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9116),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9115)
                        },
                        new
                        {
                            Id = 47,
                            Baslik = "Örnek Yazı 47",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9118),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9118)
                        },
                        new
                        {
                            Id = 48,
                            Baslik = "Örnek Yazı 48",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9120),
                            Icerik = "\r\n                    <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                    <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 3, 169, DateTimeKind.Local).AddTicks(9120)
                        });
                });

            modelBuilder.Entity("Gunluk.Data.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Genel"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Gezilerim"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Mutfağım"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "İş Dünyam"
                        });
                });

            modelBuilder.Entity("Gunluk.Data.Gonderi", b =>
                {
                    b.HasOne("Gunluk.Data.Kategori", "Kategori")
                        .WithMany("Gonderiler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("Gunluk.Data.Kategori", b =>
                {
                    b.Navigation("Gonderiler");
                });
#pragma warning restore 612, 618
        }
    }
}
